vpc-name      = "jenkins-vpc"
igw-name      = "jenkins-igw"
subnet-name   = "jenkins-subnet"
rt-name       = "jenkins-route-table"
sg-name       = "jenkins-sg"
instance-name = "jenkins-server"
key-name      = "sonuitkeypair"
iam-role      = "jenkins-iam-role"